### ISSUE TITLE
Here is your feedback for Lab Report 2:

### ISSUE THREAD

**Issue by sidbagdi** [JL-Young/cse15l-lab-reports#2]
Here is your feedback for Lab Report 2:

- [x] Correct screenshot of code diff page
- [ ] Correct failure inducing test file - 1
- [x] Correct failure inducing test file - 2
- [x] Correct failure inducing test file - 3
- [x] Screenshot of symptom output that caused the failure for test file - 1
- [x] Screenshot of symptom output that caused the failure for test file - 2
- [x] Screenshot of symptom output that caused the failure for test file - 3
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 1
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 2
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 3
- [x] Correct markdown formatting
- [x] Lab report is on its own page, not the index page
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

The main index page for your website should have links to all the lab reports.
The Failure Input Inducing file should be an md file as it is not possible to understand what was the failure input. Please link to the md file! Do it for all 3 cases and you should be good to go!
 

--------

**Comment by sidbagdi** [comment]
Comments addressed.

**Comment by JL-Young** [comment]
Feedback received. Failure inducing test file has been fixed.
